name: expense_tracker
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  intl: ^0.19.0
  animations: ^2.0.5
  dropdown_button2: ^2.3.8
  

  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - ./assets/profile.jpg